name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Info (التحقق من الملفات)
        run: |
          echo "=== Current Path ==="
          pwd
          echo "=== Directory Contents ==="
          ls -la

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git unzip wget zip autoconf automake libtool pkg-config zlib1g-dev libncurses-dev libtinfo-dev cmake libffi-dev libssl-dev ccache
          pip3 install --upgrade pip setuptools wheel
          pip3 install buildozer cython virtualenv

      - name: Build APK
        run: yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DownSuVid-APK
          path: bin/*.apk
